### ISSUE TITLE
Anonymous Applications

### ISSUE THREAD

**Issue by Chef-Code** [CS297Sp16/LCC_Co-op_Site#106]
![anonymous_application_lcc_co-op](https://cloud.githubusercontent.com/assets/11050274/15987019/efabb014-2fce-11e6-8078-7a88a835281b.PNG)
Applications with no information associated with it

**Comment by Kethsar** [comment]
It's been fixed, as can be seen by the two that do have information. The first two were the first applications submitted, and were just never deleted after I fixed the issue.

**Comment by Chef-Code** [comment]
Oh gotcha
