### ISSUE TITLE
Invitation Rescinds Redirect to Non-Existent Page

### ISSUE THREAD

**Issue by Kethsar** [CS297Sp16/LCC_Co-op_Site#86]
The redirect after confirming the deletion of an invite redirects to the old, and no longer available, invite list that used to be in the base Control Panel controller.

**Comment by Chef-Code** [comment]
@Kethsar 
`        [HttpPost, ActionName("Rescind"), Authorize(Roles = "Admin, Coordinator"),
            ValidateAntiForgeryToken]
        public ActionResult ConfirmRescind(string id)
        {
            RegisterInvite inv = db.Invites.Find(id);
            if (inv.UserType == RegisterInvite.AccountType.Coordinator && !User.IsInRole("Admin"))
            {
                ViewBag.Message = "You must be an administrator to rescind a coordinator's registration invite.";
                return View(inv);
            }
            else
            {
                db.Invites.Remove(inv);
                db.SaveChanges();
            }

```
        return RedirectToAction("InviteList");
    }`
```

this points to a View we no longer have

**Comment by Chef-Code** [comment]
I found it trying to merge, there is no view called InviteList

**Comment by Kethsar** [comment]
Yes, I know the cause. It's my fault. I'm just putting it up as a bug to remind myself or someone else to fix it.

**Comment by Chef-Code** [comment]
ok

**Comment by droopy25** [comment]
Has this been fixed now?

**Comment by Kethsar** [comment]
Fixed with pull request #89
