### ISSUE TITLE
Registration user experience

### ISSUE THREAD

**Issue by ProfBird** [CS297Sp16/LCC_Co-op_Site#99]
When I tried to register, I kept getting a validation error saying that I hadn't selected a major. I finally realized that I needed to click the "add" button. (duh!) 

On many web sites you can select an item from a drop-down list just by, well, selecting it. Maybe yours could work that way, without the "add" button, or you could make it clearer that the button needs to be clicked.

**Comment by Kethsar** [comment]
Possible fix (for us): If no majors are in the currently checked POSTed array, use the currently selected major in the select list.

Thanks Brian.

**Comment by Chef-Code** [comment]
Sounds like an easy fix. So default to the selectedIndex or selectedValue... I can never remeber exactly which one it is... either way

**Comment by Kethsar** [comment]
@Chef-Code Yeah, I'll probably integrate it while finishing up the Account controller.

**Comment by Kethsar** [comment]
Implemented with pull request #101
